name: Build iOS IPA
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-ios-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm run build

      - name: Create build-mobile directory
        run: |
          mkdir -p build-mobile
          echo '<!DOCTYPE html><html><head><title>Shatibi</title></head><body><h1>Shatibi App</h1></body></html>' > build-mobile/index.html

      - name: Setup Capacitor
        run: |
          rm -rf ios
          npx cap add ios
          npx cap sync ios

      - name: Build iOS App for Device (unsigned)
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Debug \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE=""

      - name: Create IPA
        run: |
          cd ios/App
          mkdir -p Payload
          cp -r /Users/runner/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug-iphoneos/App.app Payload/ 2>/dev/null || \
          cp -r build/Debug-iphoneos/App.app Payload/
          zip -r shatibi-unsigned.ipa Payload/
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: shatibi-ios-ipa
          path: ios/App/shatibi-unsigned.ipa
